### ISSUE TITLE
Create new User failes

### ISSUE THREAD

**Issue by JBinggi** [OnePlc/PLC_X_User#6]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.4

#### Summary

Statement could not be executed (HY000 - 1364 - Field 'created_by' doesn't have a default value)

#### Current behavior

Can't create a new User over the Button Add User, php Error while saving

#### How to reproduce

Goto Modul Users and add a new User with Username, Email, Name and Password and hit Save User

**Comment by Praesidiarius** [comment]
fixed in 1.0.5.2
